### ISSUE TITLE
Spotify errors each new page with userscript installed and running

### ISSUE THREAD

**Issue by trebante** [cvzi/Spotify-Genius-Lyrics-userscript#10]
***if it matters, I'm using Tampermokey BETA  4.14.6143 with Chrome beta 93.0.4577.51***
Spotify shows an "Something went wrong" error each time I attempt to change pages within spotify
![This was captured with the sidebar up navigating to "your library"](https://user-images.githubusercontent.com/74837381/130999809-d3805e07-2e92-4976-af61-2c0df21de603.png)

**Comment by cvzi** [comment]
Thanks for the report. 
It is happening for me as well on Firefox with Tampermonkey.
I am not sure why it's happening, I will look into it

**Comment by cvzi** [comment]
The problem was that the script removes the "Upgrade to premium" and "install app" button. I changed it to only hide but not remove the button, that seems to solve it.
