### ISSUE TITLE
Styling For Spotify Theme

### ISSUE THREAD

**Issue by mortyobnoxious** [cvzi/Spotify-Genius-Lyrics-userscript#2]
Thank you for this script.

Is it possible to change it to go well with the Spotify theme as in picture below and remove some unnecessary elements within the iframe?

![image](https://user-images.githubusercontent.com/42044258/55282531-7d8a0180-5356-11e9-8257-9133acfbcb50.png)

**Comment by cvzi** [comment]
I commited a first draft (7427b6f5db7eda5c6d056bc268246678c302bcb9). Maybe you can test it a bit, I don't have too much time right now.

I added an option to select a theme and to disable the annotations

**Comment by mortyobnoxious** [comment]
thank you, it works great for now.
