### ISSUE TITLE
Error fetching lyrics inside Spotify Web Player

### ISSUE THREAD

**Issue by wiserdi** [cvzi/Spotify-Genius-Lyrics-userscript#21]
![image](https://user-images.githubusercontent.com/104732528/231105608-ef9e8ed7-53fe-4920-966c-5d5d0bb6e654.png)

**Comment by cvzi** [comment]
Does it always happen or just with that song?

**Comment by wiserdi** [comment]
Thanks for the reply. It happens all the time. 
I use Chrome. Version 111.0.5563.147 (Official Build) (64-bit)
The script is here [](https://greasyfork.org/en/scripts/377439-spotify-genius-lyrics)

**Comment by wiserdi** [comment]
[https://greasyfork.org/en/scripts/377439-spotify-genius-lyrics](url)

**Comment by wiserdi** [comment]
In Version 114.0.5696.0 (Official Build) dev (64-bit) it works fine. The Dev version doesn't have any ad-blocker while Chrome. Version 111.0.5563.147 (Official Build) (64-bit) has some. Maybe it's due to the ad-blockers.

**Comment by cvzi** [comment]
Ad blocker could theoretically interfere with it, but I don't see why an ad blocker would block requests to [genius.com](https://genius.com/). 

I am using Chrome on Windows Version 112.0.5615.50 (Official Build) (64-bit) with Tampermonkey 4.18.1 and it works.

**Comment by cvzi** [comment]
Could you copy the whole error message (from the dialog in your screenshot) and post it here?

**Comment by wiserdi** [comment]
It returned:
`{"meta":{"status":200},"response":{"sections":[{"type":"song","hits":[{"highlights":[],"index":"song","type":"song","result":{"_type":"song","annotation_count":4,"api_path":"/songs/374596","artist_names":"Tiësto","full_title":"Red Lights by Tiësto","header_image_thumbnail_url":"https://images.genius.com/852fd67e7d84b623107b2deb04d79ba2.300x300x1.jpg","header_image_url":"https://images.genius.com/852fd67e7d84b623107b2deb04d79ba2.1000x1000x1.jpg","id":374596,"instrumental":false,"language":"en","lyrics_owner_id":256152,"lyrics_state":"complete","lyrics_updated_at":1551110182,"path":"/Tiesto-red-lights-lyrics","pyongs_count":16,"relationships_index_url":"https://genius.com/Tiesto-red-lights-sample","release_date_components":{"year":2013,"month":12,"day":13},"release_date_for_display":"December 13, 2013","release_date_with_abbreviated_month_for_display":"Dec. 13, 2013","song_art_image_thumbnail_url":"https://images.genius.com/852fd67e7d84b623107b2deb04d79ba2.300x300x1.jpg","song_art_image_url":"https://images.genius.com/852fd67e7d84b623107b2deb04d79ba2.1000x1000x1.jpg","stats":{"unreviewed_annotations":2,"hot":false,"pageviews":36539},"title":"Red Lights","title_with_featured":"Red Lights","updated_by_human_at":1607443842,"url":"https://genius.com/Tiesto-red-lights-lyrics","featured_artists":[],"primary_artist":{"_type":"artist","api_path":"/artists/1082","header_image_url":"https://images.genius.com/f41563b6bbecb9f85b3972f7742278a0.1000x750x1.jpg","id":1082,"image_url":"https://images.genius.com/e291c5b283776be966783a199415d02e.514x514x1.jpg","index_character":"t","is_meme_verified":false,"is_verified":false,"name":"Tiësto","slug":"Tiesto","url":"https://genius.com/artists/Tiesto"}}},{"highlights":[],"index":"song","type":"song","result":{"_type":"song","annotation_count":1,"api_path":"/songs/1835225","artist_names":"Tiësto","full_title":"Red Lights (Extended Version) by Tiësto","header_image_thumbnail_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.300x300x1.jpg","header_image_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.600x600x1.jpg","id":1835225,"instrumental":false,"language":"en","lyrics_owner_id":1549345,"lyrics_state":"complete","lyrics_updated_at":1431626791,"path":"/Tiesto-red-lights-extended-version-lyrics","pyongs_count":null,"relationships_index_url":"https://genius.com/Tiesto-red-lights-extended-version-sample","release_date_components":{"year":2014,"month":1,"day":null},"release_date_for_display":"January 2014","release_date_with_abbreviated_month_for_display":"Jan. 2014","song_art_image_thumbnail_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.300x300x1.jpg","song_art_image_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.600x600x1.jpg","stats":{"unreviewed_annotations":0,"hot":false},"title":"Red Lights (Extended Version)","title_with_featured":"Red Lights (Extended Version)","updated_by_human_at":1608194286,"url":"https://genius.com/Tiesto-red-lights-extended-version-lyrics","featured_artists":[],"primary_artist":{"_type":"artist","api_path":"/artists/1082","header_image_url":"https://images.genius.com/f41563b6bbecb9f85b3972f7742278a0.1000x750x1.jpg","id":1082,"image_url":"https://images.genius.com/e291c5b283776be966783a199415d02e.514x514x1.jpg","index_character":"t","is_meme_verified":false,"is_verified":false,"name":"Tiësto","slug":"Tiesto","url":"https://genius.com/artists/Tiesto"}}},{"highlights":[],"index":"song","type":"song","result":{"_type":"song","annotation_count":1,"api_path":"/songs/1835298","artist_names":"Tiësto","full_title":"Red Lights (twoloud Remix) by Tiësto","header_image_thumbnail_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.300x300x1.jpg","header_image_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.600x600x1.jpg","id":1835298,"instrumental":false,"language":"en","lyrics_owner_id":1549345,"lyrics_state":"complete","lyrics_updated_at":1607443935,"path":"/Tiesto-red-lights-twoloud-remix-lyrics","pyongs_count":null,"relationships_index_url":"https://genius.com/Tiesto-red-lights-twoloud-remix-sample","release_date_components":{"year":2014,"month":1,"day":null},"release_date_for_display":"January 2014","release_date_with_abbreviated_month_for_display":"Jan. 2014","song_art_image_thumbnail_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.300x300x1.jpg","song_art_image_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.600x600x1.jpg","stats":{"unreviewed_annotations":0,"hot":false},"title":"Red Lights (twoloud Remix)","title_with_featured":"Red Lights (twoloud Remix)","updated_by_human_at":1608194181,"url":"https://genius.com/Tiesto-red-lights-twoloud-remix-lyrics","featured_artists":[],"primary_artist":{"_type":"artist","api_path":"/artists/1082","header_image_url":"https://images.genius.com/f41563b6bbecb9f85b3972f7742278a0.1000x750x1.jpg","id":1082,"image_url":"https://images.genius.com/e291c5b283776be966783a199415d02e.514x514x1.jpg","index_character":"t","is_meme_verified":false,"is_verified":false,"name":"Tiësto","slug":"Tiesto","url":"https://genius.com/artists/Tiesto"}}},{"highlights":[],"index":"song","type":"song","result":{"_type":"song","annotation_count":1,"api_path":"/songs/1835274","artist_names":"Tiësto","full_title":"Red Lights (Fred Falke Remix) by Tiësto","header_image_thumbnail_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.300x300x1.jpg","header_image_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.600x600x1.jpg","id":1835274,"instrumental":false,"language":"en","lyrics_owner_id":1549345,"lyrics_state":"complete","lyrics_updated_at":1431626817,"path":"/Tiesto-red-lights-fred-falke-remix-lyrics","pyongs_count":null,"relationships_index_url":"https://genius.com/Tiesto-red-lights-fred-falke-remix-sample","release_date_components":{"year":2014,"month":1,"day":null},"release_date_for_display":"January 2014","release_date_with_abbreviated_month_for_display":"Jan. 2014","song_art_image_thumbnail_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.300x300x1.jpg","song_art_image_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.600x600x1.jpg","stats":{"unreviewed_annotations":0,"hot":false},"title":"Red Lights (Fred Falke Remix)","title_with_featured":"Red Lights (Fred Falke Remix)","updated_by_human_at":1608194653,"url":"https://genius.com/Tiesto-red-lights-fred-falke-remix-lyrics","featured_artists":[],"primary_artist":{"_type":"artist","api_path":"/artists/1082","header_image_url":"https://images.genius.com/f41563b6bbecb9f85b3972f7742278a0.1000x750x1.jpg","id":1082,"image_url":"https://images.genius.com/e291c5b283776be966783a199415d02e.514x514x1.jpg","index_character":"t","is_meme_verified":false,"is_verified":false,"name":"Tiësto","slug":"Tiesto","url":"https://genius.com/artists/Tiesto"}}},{"highlights":[],"index":"song","type":"song","result":{"_type":"song","annotation_count":1,"api_path":"/songs/1835633","artist_names":"Tiësto","full_title":"Red Lights (Afrojack Remix) by Tiësto","header_image_thumbnail_url":"https://images.genius.com/9217d2dc376dce6d282669f419d1616c.300x169x1.jpg","header_image_url":"https://images.genius.com/9217d2dc376dce6d282669f419d1616c.1000x563x1.jpg","id":1835633,"instrumental":false,"language":"en","lyrics_owner_id":1549345,"lyrics_state":"complete","lyrics_updated_at":1607442929,"path":"/Tiesto-red-lights-afrojack-remix-lyrics","pyongs_count":null,"relationships_index_url":"https://genius.com/Tiesto-red-lights-afrojack-remix-sample","release_date_components":{"year":2014,"month":2,"day":23},"release_date_for_display":"February 23, 2014","release_date_with_abbreviated_month_for_display":"Feb. 23, 2014","song_art_image_thumbnail_url":"https://images.genius.com/25ee1707aa51973c270a002db4d34811.300x300x1.jpg","song_art_image_url":"https://images.genius.com/25ee1707aa51973c270a002db4d34811.600x600x1.jpg","stats":{"unreviewed_annotations":0,"hot":false},"title":"Red Lights (Afrojack Remix)","title_with_featured":"Red Lights (Afrojack Remix)","updated_by_human_at":1608194450,"url":"https://genius.com/Tiesto-red-lights-afrojack-remix-lyrics","featured_artists":[],"primary_artist":{"_type":"artist","api_path":"/artists/1082","header_image_url":"https://images.genius.com/f41563b6bbecb9f85b3972f7742278a0.1000x750x1.jpg","id":1082,"image_url":"https://images.genius.com/e291c5b283776be966783a199415d02e.514x514x1.jpg","index_character":"t","is_meme_verified":false,"is_verified":false,"name":"Tiësto","slug":"Tiesto","url":"https://genius.com/artists/Tiesto"}}},{"highlights":[],"index":"song","type":"song","result":{"_type":"song","annotation_count":1,"api_path":"/songs/1835665","artist_names":"Tiësto","full_title":"Red Lights (Blame Remix) by Tiësto","header_image_thumbnail_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.300x300x1.jpg","header_image_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.600x600x1.jpg","id":1835665,"instrumental":false,"language":"en","lyrics_owner_id":1549345,"lyrics_state":"complete","lyrics_updated_at":1431627029,"path":"/Tiesto-red-lights-blame-remix-lyrics","pyongs_count":null,"relationships_index_url":"https://genius.com/Tiesto-red-lights-blame-remix-sample","release_date_components":{"year":2014,"month":1,"day":null},"release_date_for_display":"January 2014","release_date_with_abbreviated_month_for_display":"Jan. 2014","song_art_image_thumbnail_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.300x300x1.jpg","song_art_image_url":"https://images.genius.com/302e0224f22866fd46639811b94a8974.600x600x1.jpg","stats":{"unreviewed_annotations":0,"hot":false},"title":"Red Lights (Blame Remix)","title_with_featured":"Red Lights (Blame Remix)","updated_by_human_at":1608194671,"url":"https://genius.com/Tiesto-red-lights-blame-remix-lyrics","featured_artists":[],"primary_artist":{"_type":"artist","api_path":"/artists/1082","header_image_url":"https://images.genius.com/f41563b6bbecb9f85b3972f7742278a0.1000x750x1.jpg","id":1082,"image_url":"https://images.genius.com/e291c5b283776be966783a199415d02e.514x514x1.jpg","index_character":"t","is_meme_verified":false,"is_verified":false,"name":"Tiësto","slug":"Tiesto","url":"https://genius.com/artists/Tiesto"}}},{"highlights":[],"index":"song","type":"song","result":{"_type":"song","annotation_count":1,"api_path":"/songs/2187260","artist_names":"Tiësto","full_title":"Red Lights - Radio Edit by Tiësto","header_image_thumbnail_url":"https://images.genius.com/e291c5b283776be966783a199415d02e.300x300x1.jpg","header_image_url":"https://images.genius.com/e291c5b283776be966783a199415d02e.514x514x1.jpg","id":2187260,"instrumental":false,"language":"en","lyrics_owner_id":1549345,"lyrics_state":"complete","lyrics_updated_at":1436816349,"path":"/Tiesto-red-lights-radio-edit-lyrics","pyongs_count":null,"relationships_index_url":"https://genius.com/Tiesto-red-lights-radio-edit-sample","release_date_components":null,"release_date_for_display":null,"release_date_with_abbreviated_month_for_display":null,"song_art_image_thumbnail_url":"https://images.genius.com/e291c5b283776be966783a199415d02e.300x300x1.jpg","song_art_image_url":"https://images.genius.com/e291c5b283776be966783a199415d02e.514x514x1.jpg","stats":{"unreviewed_annotations":0,"hot":false},"title":"Red Lights - Radio Edit","title_with_featured":"Red Lights - Radio Edit","updated_by_human_at":1447111578,"url":"https://genius.com/Tiesto-red-lights-radio-edit-lyrics","featured_artists":[],"primary_artist":{"_type":"artist","api_path":"/artists/1082","header_image_url":"https://images.genius.com/f41563b6bbecb9f85b3972f7742278a0.1000x750x1.jpg","id":1082,"image_url":"https://images.genius.com/e291c5b283776be966783a199415d02e.514x514x1.jpg","index_character":"t","is_meme_verified":false,"is_verified":false,"name":"Tiësto","slug":"Tiesto","url":"https://genius.com/artists/Tiesto"}}}]}],"next_page":2}}`

**Comment by wiserdi** [comment]
> Ad blocker could theoretically interfere with it, but I don't see why an ad blocker would block requests to [genius.com](https://genius.com/).
> 
> I am using Chrome on Windows Version 112.0.5615.50 (Official Build) (64-bit) with Tampermonkey 4.18.1 and it works.
Now it's back to normal. Still with AD-blockers on while no errors happened. 
The error message is not copiable as plain text and now I don't have it. 
So if this problem happens next time, I'll promptly tell you.

![image](https://user-images.githubusercontent.com/104732528/231911199-16329e36-e46b-4714-8718-99f81eac8b74.png)


Thanks for the maintenance.

**Comment by cvzi** [comment]
Thanks for the report! I'll close this issue for now (you can still comment if it happens again)
