### ISSUE TITLE
Formatting Issues with Themes other that 'Genius (Default)'

### ISSUE THREAD

**Issue by Demaar** [cvzi/Spotify-Genius-Lyrics-userscript#27]
There is a large empty space between Title and Lyrics seemingly caused by the new 'Track # on [Album]' display.
Also, the Spotify Theme does not have proper Line Break.

**Comment by cvzi** [comment]
The empty space should be fixed now. Not sure about the line breaks, I didn't see the problem.

**Comment by Demaar** [comment]
Here, some images.
![Screenshot 2023-08-28 132543](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/assets/6378460/9c11561f-73d6-426a-9ade-1e33f62fd1ae)
![Screenshot 2023-08-28 132629](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/assets/6378460/601df129-0397-4ca6-bf10-b9ae15246527)
This is on Chromium. Brave specifically, but Iron looks the same.

On Firefox the empty Space is gone however it has this below the Lyrics. 
The black shape at the bottom is the top of the Facebook F.
![Screenshot 2023-08-28 133142](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/assets/6378460/21d90d6b-3bc6-4a85-9f13-02b9b5b5d83e)

**Comment by cvzi** [comment]
Possibly the caches of the script were not updated. I have posted a new version.
