### ISSUE TITLE
[Firefox] Lyrics stuck on loading

### ISSUE THREAD

**Issue by HDark15** [cvzi/Spotify-Genius-Lyrics-userscript#29]
Firefox with Violentmonkey, not working only on Spotify. This is the error when it active
```
TypeError: 'setTimeout' called on an object that does not implement interface Window. sandbox eval code:124:28
TypeError: 'setInterval' called on an object that does not implement interface Window. sandbox eval code:4907:73
```
The button not show up and this is the error when clicking "Show lyrics"
```
TypeError: 'requestAnimationFrame' called on an object that does not implement interface Window. sandbox eval code:3873:10
```
It stuck on loading, I can open settings and search
![firefox_7302FwDbny](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/assets/34807171/0d999b03-355a-40aa-be20-5e832bf036ca)

**Comment by cvzi** [comment]
I will check on the weekend

**Comment by cvzi** [comment]
Happens only with Violentmonkey, Tampermonkey still works. 
It should be possible to fix it for Violentmonkey.

**Comment by ayathedoggo** [comment]
Same issue here with Firefox and Violentmonkey. Switching to Tampermonkey 'til fixed. <3

**Comment by cyfung1031** [comment]
Can produce on my side. I will fix this issue.

**Comment by cyfung1031** [comment]
The root cause is that there is a commit in Apr 20, 2024 which added `@grant unsafeWindow` in the script.
This would change the `window` variable. The original method binding was incorrect.

Now issue should be fixed.

**Comment by cvzi** [comment]
Oh right, that is not supposed to be there. I tried using unsafeWindow to access the Spotify javascript to close the "Now Playing"-view, but that didn't work reliably. I'll remove it.

**Comment by cyfung1031** [comment]
Previously, you faced the issue that setTimeout/setInterval is modified by Spotify and the timer could not work, so you tried to add the code to obtain the native setTimeout/setInterval.

Now, the issue become the environment is already isolated so the obtaining native method is no longer required.

I will PR the changes required to omit unsafeWindow and make sure it is isolated from the page context.
