### ISSUE TITLE
[Violentmonkey, Brave] Queue closes with script enabled

### ISSUE THREAD

**Issue by ayathedoggo** [cvzi/Spotify-Genius-Lyrics-userscript#30]
Hiya. Love this thing now that Spotify's lyrics have been all wack. Thank you for making it.

I noticed an issue with the queue option with the script enabled. It closes after a few seconds.
Confirmed issue on Brave, Chrome, Firefox.
Confirmed issue still present with no other extensions.
Confirmed issue not present without userscript enabled, of course.

<3

https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/assets/105717495/26ea005a-92d0-4d5c-bcc6-afa8d9fe0ad7

**Comment by cvzi** [comment]
Looks like something has changed with the Spotify website again. It is supposed to close the "Now Playing View" but not the queue.

You can disable 'Hide Spotify's "Now Playing View"' in the options of the script, until I can fix it.

**Comment by cvzi** [comment]
Should be solved now

**Comment by ayathedoggo** [comment]
Can confirm. You do great work! Thank you!
