### ISSUE TITLE
Way too laggy on spotify 

### ISSUE THREAD

**Issue by Malmasri15** [cvzi/Spotify-Genius-Lyrics-userscript#34]
this is way too laggy for my pc it keeps lagging sm that every song takes 5 seconds to play and after it it takes 5 more seconds and most of the time it crashes spotify making it unable to play anything for 10 seconds for it to load on microsoft edge please fix this because music is basically unplayable

![Screenshot 2024-05-13 142806](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/assets/110121174/03977499-c939-4ddd-b6b4-f6f31de58687)

**Comment by cvzi** [comment]
I don't have Edge at the moment, maybe I can check on the weekend on another computer. Which userscript addon do you use? Tampermonkey?

**Comment by Malmasri15** [comment]
yeah i use Tampermonkey thank you so much

**Comment by cvzi** [comment]
I can reproduce it on Edge and Chrome. It much more noticeable on Edge though. Firefox seems to work normal.

**Comment by Malmasri15** [comment]
im really sorry im making you do this its just very laggy :<

**Comment by cvzi** [comment]
@cyfung1031 Could this be caused by `LZString.compressToUTF16()`. If I remove LZString and just store the normal JSON strings instead, it feels faster on Edge.

**Comment by cyfung1031** [comment]
> @cyfung1031 Could this be caused by `LZString.compressToUTF16()`. If I remove LZString and just store the normal JSON strings instead, it feels faster on Edge.

If the functions change to 
`LZString.compress` and `LZString.decompress`
(Just change the name)

Would the issue resolve?

**Comment by cvzi** [comment]
@Malmasri15 Could you disable/Uninstall the script and then try this test version instead:

https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/raw/test_no_-lzstring/SpotifyGeniusLyrics.user.js

**Comment by Malmasri15** [comment]
Im gonna use it for a while and see if it lags thank you so much :>

![image](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/assets/110121174/8c6d65a3-265c-40fb-b32e-6f8f55c71d69)

**Comment by cyfung1031** [comment]
> No, doesn't help and additionally the data gets corrupted and `JSON.parse` fails

The previous cache needs to be cleared first.

Anyway, I cannot reproduce the issue on my Edge on macbook.

Please try the following script

https://raw.githubusercontent.com/cvzi/genius-lyrics-userscript/4f558d86ebfc597513d623d06a37bf84cf007136/GeniusLyrics.js

------

I have searched on the web but seems no similar issue created in LZString.

If it is still laggy on the default compress/decompress, we should restore to the no LZString.

**Comment by Malmasri15** [comment]
there seems to be some errors in the script you gave 

![image](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/assets/110121174/11698510-c668-4ecc-b517-b3d8c0f8dc61)
![image](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/assets/110121174/d281b0f9-c17a-44d6-b208-d82df62369eb)
![image](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/assets/110121174/7d9bf607-9048-4e3a-92c8-5ff4ce97cee9)
![image](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/assets/110121174/8aad1dbc-9f02-41e5-be03-b8cd600ac2c1)

**Comment by cyfung1031** [comment]
> @Malmasri15 You can ignore those errors. Does this version work better than the normal version?
> 
> @cyfung1031 ok, compress/decompress works without errors, but it still lags then same as compressToUTF16. I tested on two Windows machines with Edge.
> 
> I don't see the "This page is responding" dialog, but the page stops responding for short time It is also noticeable when opening the script options, because of the measuring the string length, it takes ~5 seconds to open the options.
> 
> Maybe we can just disable lzstring for Edge on Windows?
> 
> Edit: There is another issue with possibly the same problem [cvzi/Youtube-Music-Genius-Lyrics-userscript#18](https://github.com/cvzi/Youtube-Music-Genius-Lyrics-userscript/issues/18)

I am thinking that we might add an option to the menu. So people can enable or disable it.
By default, it is enabled except for Edge.

(As it is no different, just use `compressToUTF16` and `decompressToUTF16`)

**Comment by Malmasri15** [comment]
@Malmasri15 You can ignore those errors. Does this version work better than the normal version?

Yes It does thank you so much its much more smoother and a lot less laggy I think its perfect rn it doesn't need anymore fixes depends on what you see from your end tho :>
