### ISSUE TITLE
Disable suggestion to submit new lyrics to Genius if user is not actively premium

### ISSUE THREAD

**Issue by maanisim** [cvzi/Spotify-Genius-Lyrics-userscript#35]
Hello there,

I recommend turning this off for users who are not actively using the Spotify premium, as indicated by the message "Enjoy lyrics on Spotify Premium." in the middle, because not all lyrics are available.

Thanks

**Comment by cvzi** [comment]
Makes sense. I was not aware lyrics were a premium feature.

**Comment by maanisim** [comment]
It has been so for only a month - https://techcrunch.com/2024/05/02/spotify-is-quietly-moves-lyrics-behind-a-paywall/?guccounter=1

**Comment by cvzi** [comment]
This should work now.

Thanks for the report!
