### ISSUE TITLE
Automatic scrolling not working

### ISSUE THREAD

**Issue by erktiky** [cvzi/Spotify-Genius-Lyrics-userscript#37]
A few days ago songs stopped automatically switching and automatic scrolling stopped working, now it seems like the first issue is fixed but automatic scrolling still doesn't work. When I toggle it on literally nothing changes.

Btw great script, love it

**Comment by cvzi** [comment]
Thanks for the report. 

Yes it seems like Spotify is changing their website often at the moment. I have already updated the script twice, but I guess they changed something again. I'll take a look later.

**Comment by cvzi** [comment]
Should be fixed now
