### ISSUE TITLE
Suggestion - pop out lyrics

### ISSUE THREAD

**Issue by erktiky** [cvzi/Spotify-Genius-Lyrics-userscript#38]
I've been using this addon for a few weeks now and I like it, but it would be a great addition if you could pop out the lyrics into a different window and it would maintain features such as auto-scrolling or song switching. Also, there could be a button that would toggle always-on-top, so you could see the lyrics which would also be auto-scrolling while doing something else.

**Comment by cvzi** [comment]
I have thought about this before. Maybe I'll take another look

ref #53 #57
