### ISSUE TITLE
New genius.com page design

### ISSUE THREAD

**Issue by cvzi** [cvzi/Spotify-Genius-Lyrics-userscript#4]
Apparently genius.com is [phasing in a new page design](https://genius.com/discussions/377926-The-2020-genius-song-page-redesign). This will break the "Spotify theme" completely. Parts of the "Genius theme" are also broken.

https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/blob/ba03cca540d7b4b8a69d31e216fb9c122ea54be3/SpotifyGeniusLyrics.user.js#L507-L516

**Comment by Shazgul** [comment]
Error:   Unknown genius page design
Genius:  https://genius.com/Omik-k-kamikaze-lyrics

**Comment by cvzi** [comment]
Thanks for the report!

We are doing some major updates to the script at the moment. I think that will resolve the problem

**Comment by cvzi** [comment]
This should be fixed now. The script will now ignore these results like  https://genius.com/Omik-k-kamikaze-lyrics that say "Lyrics for this song have yet to be released"
