### ISSUE TITLE
could not transform the genius page

### ISSUE THREAD

**Issue by catcafeman** [cvzi/Spotify-Genius-Lyrics-userscript#40]
## here are the pics:
![2024-12-14_16-45-24](https://github.com/user-attachments/assets/b06d424d-8ecf-4e99-87e2-f2af37e9dd02)
> themeName:  Clean white
Error:      Neither "Lyrics__Container" nor "LyricsPlaceholder__Container" found
URL:        https://open.spotify.com/playlist/37i9dQZEVXbfLd6hmPibKx
Genius:     https://genius.com/Xg-iykyk-lyrics
Song:       IYKYK by XG
Browser:    Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
## when i back to the default theme , the odd zoom made me confused , and i have noticed that it won't recover as i zoom the browser 
![2024-12-14_16-50-49](https://github.com/user-attachments/assets/06d6ccb7-f7ca-4dab-b725-df25a7878735)
![2024-12-14_16-53-12](https://github.com/user-attachments/assets/19e7be69-7d05-4d46-8571-1acb98b24163)

**Comment by cvzi** [comment]
The white and Spotify theme should work again.
The "default" theme probably needs some more work to make it pretty again.
