### ISSUE TITLE
Show button

### ISSUE THREAD

**Issue by TheNolle** [cvzi/Spotify-Genius-Lyrics-userscript#6]
When we click "hide", the only way to show it again is to reload the page, can you add a "show" button?

**Comment by cvzi** [comment]
There should be a small yellow "G" in the upper right corner (on the scrollbar) to show the lyrics again.

**Comment by TheNolle** [comment]
I can't find it, all I have when I hide it is this:
![image](https://user-images.githubusercontent.com/61505071/90062460-01dcea80-dce8-11ea-87c9-25e66f5c74db.png)

**Comment by cvzi** [comment]
Thank you, I'll check what's wrong.

**Comment by cvzi** [comment]
I added a command to the Tampermonkey menu as a quick solution for now, until I find out why the button is not appearing for you

**Comment by TheNolle** [comment]
Thx! (If it helps: I use tampermonkey latest version on Brave)

**Comment by cvzi** [comment]
Can you try again now?  And what is your operating system, I believe it is not a browser issue but OS related.

**Comment by TheNolle** [comment]
Windows 10 pro, the "show button" on the settings with tampermonkey works just fine
