### ISSUE TITLE
lyrics not showing up, but the window is

### ISSUE THREAD

**Issue by RuralAnemone** [cvzi/Spotify-Genius-Lyrics-userscript#7]
the genius window show up, but there are no lyrics

(attached is a video showing that they don't exactly show up)
[spotify lyrics not working.....zip](https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/files/5811092/spotify.lyrics.not.working.zip)

this might have to do with genius's new layout (mentioned in the other issue), but I'm not sure

**Comment by cvzi** [comment]
Thank you. I see the problem as well. I believe Spotify changed something in their page

**Comment by cvzi** [comment]
I have updated it. The Spotify page had changed slightly.

**Comment by RuralAnemone** [comment]
Thank you, it works much better now!
![screenshot-open spotify com-2021 01 13-16_30_40](https://user-images.githubusercontent.com/64103005/104518109-d161eb00-55bc-11eb-8eaa-9e17d82084c0.png)
