### ISSUE TITLE
Stopped to work in Opera

### ISSUE THREAD

**Issue by jckebs1** [cvzi/Spotify-Genius-Lyrics-userscript#8]
The script does not work anymore to me.  I don't know why. There were some bugs, but it used to work well. Two days ago it stopped to work. The icon in the right side is gone. Reinstalations don't work as well.

I'm really sad. I loved it.

Browser: Opera. 
OS: Windows 10.

**Comment by cvzi** [comment]
Thanks for the report. I can confirm it does not work for me either, probably the spotify page has changed a little bit

**Comment by cvzi** [comment]
Should work again after script update

**Comment by jckebs1** [comment]
Thank you!
