### ISSUE TITLE
[Feature Request] Add keyboard shortcuts to show / hide lyrics panel

### ISSUE THREAD

**Issue by twio142** [cvzi/Spotify-Genius-Lyrics-userscript#9]
As in the title.

**Comment by cvzi** [comment]
Do you have a suggestion for key/key combination? Do you know if Spotify already has any keyboard shortcuts reserved?

**Comment by twio142** [comment]
Yes, Spotify does have its own keyboard shortcuts.
![image](https://user-images.githubusercontent.com/64556708/128548540-99612e2a-9dab-4ca9-9756-003f09501f1f.png)

I'm not good in JavaScript. I edited this script and added a shortcut `Shift L` to show the lyric panel, but I didn't manage to add one for hiding it. So if you could enable keyboard shortcut in your script (thanks in advance!), I'd probably also edit it my own way :D

**Comment by cvzi** [comment]
Yes I will add it. Probably best to use the shift L for showing and hiding.

**Comment by cvzi** [comment]
I added it, Shift+L to show and to hide again. Please test it, I am not sure if I will use it myself.

If you want to change the key combination, you can do it here:
https://github.com/cvzi/Spotify-Genius-Lyrics-userscript/blob/f221bd91c691602ede1ce1a288cb96680e74210b/SpotifyGeniusLyrics.user.js#L470-L475

**Comment by twio142** [comment]
Great! Thanks a lot 👍
